### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by brendan-mccaffrey** [flashbots/simple-arbitrage#17]
No longer a problem

**Comment by brendan-mccaffrey** [comment]
Update: I've printed the details to the error:

> unhandledRejection Error: call revert exception (method="getPairsByIndexRange(address,uint256,uint256)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.3.1)
    at Logger.makeError (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at Interface.decodeFunctionResult (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/abi/src.ts/interface.ts:384:23)
    at Object.<anonymous> (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/contracts/src.ts/index.ts:321:44)
    at step (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getPairsByIndexRange(address,uint256,uint256)',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x5EF1009b9FCD4fec3094a5564047e190D72Bd511',
  args: [ '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f', 0, 1000 ],
  transaction: {
    data: '0xab2217e40000000000000000000000005c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003e8',
    to: '0x5EF1009b9FCD4fec3094a5564047e190D72Bd511'
  }
}

**Comment by brendan-mccaffrey** [comment]
Printed the error yields: (I changed the addresses to protect private keys)

> unhandledRejection Error: call revert exception (method="getPairsByIndexRange(address,uint256,uint256)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.3.1)
    at Logger.makeError (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at Interface.decodeFunctionResult (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/abi/src.ts/interface.ts:384:23)
    at Object.<anonymous> (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/contracts/src.ts/index.ts:321:44)
    at step (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/brendanmccaffrey/Documents/company/MEV/simple-arbitrage/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getPairsByIndexRange(address,uint256,uint256)',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0xxxxx',
  args: [ '0xxxxxxx', 0, 1000 ],
  transaction: {
    data: '0xxxxxx7e40000000000000000000000005c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003e8',
    to: '0xxxxxxx'
  }
}



>
