### ISSUE TITLE
Error: call revert exception

### ISSUE THREAD

**Issue by glaksmono** [flashbots/simple-arbitrage#25]
I'm getting the following error when I'm running `npm run start`

```
/Users/glaksmono/Documents/simple-arbitrage/node_modules/@ethersproject/logger/src.ts/index.ts:205
        const error: any = new Error(message);
                           ^
Error: call revert exception (method="getPairsByIndexRange(address,uint256,uint256)", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.9)
    at Logger.makeError (/Users/glaksmono/Documents/simple-arbitrage/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/Users/glaksmono/Documents/simple-arbitrage/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at Interface.decodeFunctionResult (/Users/glaksmono/Documents/simple-arbitrage/node_modules/@ethersproject/abi/src.ts/interface.ts:326:23)
    at Object.<anonymous> (/Users/glaksmono/Documents/simple-arbitrage/node_modules/@ethersproject/contracts/src.ts/index.ts:309:44)
    at step (/Users/glaksmono/Documents/simple-arbitrage/node_modules/@ethersproject/contracts/lib/index.js:46:23)
    at Object.next (/Users/glaksmono/Documents/simple-arbitrage/node_modules/@ethersproject/contracts/lib/index.js:27:53)
    at fulfilled (/Users/glaksmono/Documents/simple-arbitrage/node_modules/@ethersproject/contracts/lib/index.js:18:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Any ideas what do I need to do?

It would also be great if someone can improve the README so that there's step by step instructions on what to do to get this code up and running

**Comment by glaksmono** [comment]
Figured this out already

**Comment by S-Abbadon** [comment]
Hi there,
could You elaborate Your solution?
Been struggling with the exact same error for the last couple days...

Thank You very much

**Comment by githuber1001** [comment]
What was the solution? I'm getting a similiar error.

**Comment by red-saint-nft** [comment]
> What was the solution? I'm getting a similiar error.

@githuber1001 found the issue? In my case it was because I deployed the contract to the wrong network.
