### ISSUE TITLE
serverError: Error: connect ETIMEDOUT 172.67.71.234:443

### ISSUE THREAD

**Issue by zhengger** [flashbots/simple-arbitrage#9]
Below is the error information:
```
  requestMethod: 'POST',
  serverError: Error: connect ETIMEDOUT 172.67.71.234:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
      at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:126:14) {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '172.67.71.234',
    port: 443
  },
  url: 'https://relay.flashbots.net'
}
```
I pinged "172.67.71.234" and it is unreachable. I do a search: https://check-host.net/check-ping?host=relay.flashbots.net. I found that there are two IPs bond with 'https://relay.flashbots.net'. One is  "172.67.71.234" which is unreachable  for me and another is "104.26.11.65". Is there a way to set "104.26.11.65" as the entry for 'https://relay.flashbots.net'? Or is there anything wrong with my code?
Many thanks!

```
>>>>>>>>>>>>>>>>>$ ping 104.26.10.65
PING 104.26.10.65 (104.26.10.65): 56 data bytes
64 bytes from 104.26.10.65: icmp_seq=0 ttl=51 time=382.503 ms
64 bytes from 104.26.10.65: icmp_seq=1 ttl=51 time=238.248 ms
64 bytes from 104.26.10.65: icmp_seq=2 ttl=51 time=425.513 ms
64 bytes from 104.26.10.65: icmp_seq=3 ttl=51 time=258.062 ms
64 bytes from 104.26.10.65: icmp_seq=4 ttl=51 time=264.377 ms
64 bytes from 104.26.10.65: icmp_seq=5 ttl=51 time=278.940 ms
```

```
>>>>>>>>>>>>>>>>>$ ping 172.67.71.234
PING 172.67.71.234 (172.67.71.234): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7

```

**Comment by zhengger** [comment]
It's reachable now. So I closed this issue.
